version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: omamori_php
    volumes:
      - ./:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: dpg-d6hfrq4r85hc739ekgi0-a.oregon-postgres.render.com
      DB_PORT: 5432
      DB_DATABASE: omamori_db
      DB_USERNAME: dayeon
      DB_PASSWORD: letFqYKHNCSeoAIHLEmKiisMINsGeQaG
    networks:
      - omamori-network

  redis:
    image: redis:alpine
    container_name: omamori_redis
    ports:
      - "6379:6379"
    networks:
      - omamori-network

networks:
  omamori-network:
    driver: bridge